# Generated by Django 4.0.3 on 2022-03-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
