# Generated by Django 4.0.3 on 2022-03-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0007_alter_students_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
    ]
