# Generated by Django 4.0.3 on 2022-03-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0002_alter_students_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
    ]
