# Generated by Django 4.0.3 on 2022-03-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0004_students_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='session_year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS_app.sessionyearmodel'),
        ),
    ]
