# Generated by Django 4.0.3 on 2022-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0005_students_session_year_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.AddField(
            model_name='students',
            name='course_id',
            field=models.ManyToManyField(default=1, null=True, to='CMS_app.courses'),
        ),
    ]
