# Generated by Django 4.0.3 on 2022-03-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0007_remove_students_course_id_students_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CMS_app.courses'),
        ),
    ]
